version: 0.2
phases:
  install:
    commands:
      - apt update; apt install zip -y
      - pip install awscli
  build:
    commands:
      - zip index.zip index.js
      - aws lambda update-function-code --function-name testlambda --zip-file fileb://index.zip
